# This workflow merges the PRs automatically if the specified conditions are met
name: Auto Merge Pull Request

on:
  check_suite:
    types:
      - completed

jobs:
  auto-merge-idp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure all checks passed
        uses: actions/github-script@v7
        id: checks
        with:
          script: |
            const pull_number = context.payload.pull_request.number;
            const checks = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });

            const allChecksPassed = checks.data.check_runs.every(check => check.conclusion === 'success');
            return allChecksPassed;

      - name: Auto-merge PR if all checks passed and PR created by IDP-dedicated user
        if: steps.checks.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            });
