# This workflow merges the PRs automatically if the specified conditions are met
name: Auto Merge Pull Request

on:
  pull_request

permissions:
  contents: write

jobs:
  automerge:
    name: Enable automerge on dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh pr merge --squash --auto "1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
