# This workflow merges the PRs automatically if the specified conditions are met
name: Auto Merge Pull Request

permissions:
  contents: write
  pull-requests: write

on:
  pull_request_target

jobs:
  auto-merge-idp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Approve the PR
        run: gh pr review --approve --body "Approved automatically as the PR originates from IDP" "${{ github.event.number }}"
      
      - name: Enable auto-merge
        run: gh pr merge --squash --auto "${{ github.event.number }}"
        env:
          GH_TOKEN: ${{ github.token }}
